name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
      
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-5-12-9
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
      
    - name: Install OpenVR and GLM
      run: vcpkg install openvr glm --triplet x64-windows
        
    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}\build

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}\build
      run: cmake $GITHUB_WORKSPACE/software -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake
    
    - name: Compile
      shell: bash
      working-directory: ${{runner.workspace}}\build
      run: cmake --build . --config Release

    - name: Package
      shell: bash
      working-directory: ${{runner.workspace}}\build
      run: cmake --build . --target package --config Release

    - name: Archive installer
      uses: actions/upload-artifact@v1
      with:
        name: installer
        path: ${{runner.workspace}}/build/RolliVR-Installer.exe