name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      
    - name: Install OpenVR and GLM
      run: |
        vcpkg install openvr glm --triplet x64-windows
      
    - name: Configure
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" ..
    
    - name: Compile
      working-directory: build
      run: cmake --build . --config Release
    
    - name: Package
      working-directory: build
      run: cmake --build . --config Release --target package
