name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
      
    - name: Install OpenVR and GLM
      run: |
        vcpkg install openvr glm --triplet x64-windows
        
    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}\build
      
    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}\build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake
    
    - name: Compile
      shell: bash
      working-directory: ${{runner.workspace}}\build
      run: cmake --build . --config Release
    
    - name: Package
      shell: bash
      working-directory: ${{runner.workspace}}\build
      run: cmake --build . --config Release --target package
